Separated QC Status
revaturelabs/caliber-2-angular pull request #145
Opened 2019-09-20 15:17 UTC by IkenoXamos

Separated QC Status into Technical Status and Soft Skill Status. Previous references to QC Status now refer to Technical Status. May need further refactoring, as all logic regarding reports and averages are factoring in only Technical Status.

2019-09-23 19:52 UTC, Quinn-Donnelly requested changes
Due to the service level changes from PR #147 there are some changes that will impact functionality of this PR. Once reviewed please re request a review

2019-09-24 20:23 UTC, RevatureGentry commented on src/app/quality-audit/components/quality-audit-list/quality-audit-list.component.ts
> -    // this.qaService.upsertQcBatchNote(this.qcBatchNote).toPromise().then(
Do we need to be making this network call?

2019-09-24 20:31 UTC, RevatureGentry requested changes
Double check that one network call being commented out. 

Can we persist both technical and soft skills QcStatus?

2019-09-24 20:31 UTC, RevatureGentry commented on src/app/quality-audit/components/quality-audit-list/quality-audit-list.component.ts
>      // this.qaService.upsertQcBatchNote(this.qcBatchNote).toPromise().then(
Does this need to be uncommented?

2019-09-24 21:49 UTC, merged

2019-09-24 21:49 UTC, RevatureGentry commented
Great work!